### ISSUE TITLE
Release a new version including #2

### ISSUE THREAD

**Issue by gwarf** [EGI-Federation/glite-info-provider-ldap#4]
Release a new version including #2.
To be pushed to UMD

**Comment by maarten-litmaath** [comment]
Hi all,
we need this in the UMD for lcg-bdii.egi.eu (sic), thanks!

**Comment by gwarf** [comment]
HI Maarten, sorry this got overlooked apparently, I will look into this.

**Comment by gwarf** [comment]
After many/too much trial and error to adapt the automatic package building and upload, the new release is finally there: https://github.com/EGI-Federation/glite-info-provider-ldap/releases/tag/v1.5.0.

**Comment by gwarf** [comment]
I will propose the package to UMD tomorrow, but in the meantime, if you want to/can test it would be welcome.

**Comment by maarten-litmaath** [comment]
Hi all,
I have compared the rpm contents with those of version 1.4.8 that currently is the only one in UMD 4: the only difference is exactly the desired patch.  I have also checked the patched script is identical to the one we use on lcg-bdii.cern.ch.  Ergo: all is good, thanks!

**Comment by gwarf** [comment]
Submitted to UMD via https://ggus.eu/index.php?mode=ticket_info&ticket_id=158767

**Comment by gwarf** [comment]
Released to UMD: https://repository.egi.eu//SW/glite-info-provider1.5.0.html
